class Brand < ActiveHash::Base
  field :brand
  create id: 1, brand: 'アーヴェヴェ'
  create id: 2, brand: 'アーカー'
  create id: 3, brand: 'アーキ'
  create id: 4, brand: 'イアパピヨネ'
  create id: 5, brand: 'イーエーピー'
  create id: 6, brand: 'イーエム'
  create id: 7, brand: 'ヴァイスヴァーサ'
  create id: 8, brand: 'ヴァレンリ'
  create id: 9, brand: 'ヴィアサザビー'
  create id: 10, brand: 'アーリッカ'
  create id: 11, brand: 'アイブイブイ'
  create id: 12, brand: 'アイムプロダクト'
  create id: 13, brand: 'アーネスト'
  create id: 14, brand: 'アイアンウッド'
  create id: 15, brand: 'アイトー'
  create id: 16, brand: 'アーノルドパーマータイムレス'
  create id: 17, brand: 'アールエフ'
  create id: 18, brand: 'アイクポッド'
  create id: 19, brand: 'アージュレス'
  create id: 20, brand: 'アースセラプティクス'
  create id: 21, brand: 'アーダブレーン'
  create id: 22, brand: 'ウィー'
  create id: 23, brand: 'エックスボックス'
  create id: 24, brand: 'ゲームボーイ'
  create id: 25, brand: 'アイスブレーカー'
  create id: 26, brand: 'アイパス'
  create id: 27, brand: 'アウトドア'
  create id: 28, brand: 'アップル'
  create id: 29, brand: 'サムスン'
  create id: 30, brand: '東芝'
  create id: 31, brand: 'カワサキ'
  create id: 32, brand: 'スズキ'
  create id: 33, brand: 'ホンダ'
  create id: 34, brand: 'ギブソン'
  create id: 35, brand: 'フェンダー'
  create id: 36, brand: 'ヤマハ'
  create id: 37, brand: 'アルパイン'
  create id: 38, brand: 'イクリプス'
  create id: 39, brand: 'いすゞ'
  create id: 40, brand: 'アサヒビール'
  create id: 41, brand: '磯自慢'
  create id: 42, brand: '一ノ蔵'
  create id: 43, brand: 'トヨタ'
  create id: 44, brand: '日産'
  create id: 45, brand: 'レクサス'
  create id: 46, brand: 'アウディ'
  create id: 47, brand: 'ベンツ'
  create id: 48, brand: 'ワーゲン'

  has_many :items
end